### PR TITLE
add skip-front-matter to default attributes

### PR DESCRIPTION
**Pull request by 251**
Files with frontmatter mess up the preview. I guess in most cases one can simply ignore it.

### CODE REVIEW

**Comment by mojavelinux** [comment]
I think this needs to be an option in the settings panel. We can still disable it by default, but there needs to be a way of disabling in case it is messing up a valid AsciiDoc document that begins with an open block.

**Comment by 251** [comment]
As option: https://github.com/251/atom-asciidoc-preview/commit/dfb56efa954a0b400b7527a16b9cca590aaa6030

**Comment by abelsromero** [comment]
I don't see any error.

BTW, I don't know if you're familiar with it, but you can automatically link Pull Request with issues using comments. Have a look at https://help.github.com/articles/closing-issues-via-commit-messages/.

**Comment by 251** [comment]
Any wishes or comments?

**Comment by anthonny** [comment]
Hi @251,
Thank you for this PR!

I'll check it tonight ;)

**Comment by jxxcarlson** [comment]
Any chance of integrating asciidoctor-latex (the html backend) with atom-asciidoc-preview?  This would open up its use by mathematicans, physicists ... anyone who uses mathematical notation.  See, for instance, this [example](http://math.noteshare.io/titlepage/208).  An issue in integrating asiidoctor-latex is Opal compatibility, but it is now solved.  Please see [issue40](https://github.com/asciidoctor/asciidoctor-latex/issues/40).  If you do look into this, there should be a switch to use asciidoctor-latex, since it something of great use to certain communities but of no use to everyone else.

**Comment by mojavelinux** [comment]
@jxxcarlson That's probably best discussed in a separate issue. I'll follow-up with my thoughts there ;)

**Pull request merged**
