### PR TITLE
feat: base directory management

### PR DESCRIPTION
**Pull request by ldez**
## Description

Advanced base directory management.
- `base_dir`

Related to #182

## Syntax example

```adoc
include::/home/ldez/foobar.doc[]
```

## Screenshots

capture du 2016-06-17 02-50-39

### CODE REVIEW

**Comment by ldez** [comment]
This PR must be validated by @mojavelinux and @Mogztter.

**Comment by mojavelinux** [comment]
Is it possible to disable the custom base directory input when the automatic box is checked?

I like this feature. I'm not sure about the wording though. How about:

```
[ ] Automatically set base directory to match document directory. 
```

Another possible approach is to have only one option and recognize a special value for matching the document directory. For example:

```
Base directory
Use the value {docdir} to make the base directory match the document directory.
[______________________________________________________]
```

**Comment by ldez** [comment]
1. it's not possible.

2. the second is not possible because it's 3 behaviors not 2:
- checked 'auto' use doc path as `base_dir`
- unchecked 'auto' allow absolute path (no `base_dir`)
- define 'custom' disallow absolute path and define a new `base_dir`

**Comment by mojavelinux** [comment]
I understand about (1).

As for (2), I still think we can represent it as a single input field. We can have a value the represents "do not set" such as `nil` or `-`, a value which means auto, which I think works best as `{docdir}` because it is clear. Any other value is just passed through.

I'm not saying that's the right approach, but that it is possible. What we need to determine is whether it is simpler to have a single input field or have a check box with an override/custom value.

**Comment by ldez** [comment]
I'm agree with you, my problem is what Atom allow as option's type: it's very limited.

I'm want the best user friendly system, and specific values without suggest box are not really user friendly.

This is why I had split the configuration in two options but I'm not really happy with this.

**Comment by ldez** [comment]
After more reflexion, I think your proposition is better than mine.

**Comment by ldez** [comment]
see my problem:

anim

**Comment by ldez** [comment]
New proposal:

capture du 2016-06-18 14-46-21

**Comment by Mogztter** [comment]
If the field is blank, the default value is applied ? (ie. the actual value will be `{docdir}`) ?
If this is the case, I t think it's unnecessary to say "Use the value `{docdir}` to make the base directory match the document directory". As a user, if I want this behavior, I will simply use the default value and clear the field (this is simpler than typing `{docdir}`) no ?

**Comment by ldez** [comment]
New proposal:
capture du 2016-06-18 19-28-17

**Comment by Mogztter** [comment]
Perfect :ok_hand:

**Comment by mojavelinux** [comment]
Nice work!

**Pull request merged**
