### PR TITLE
refactor: move base directory construct

### PR DESCRIPTION
**Pull request by ldez**
## Description

Move the construct of `base_dir` from `worker.coffee` to `attributes-builder.coffee`

### CODE REVIEW

**Comment by mojavelinux** [comment]
This pull request made me aware of the fact that this plugin is mixing the terms "attributes" and "options". These are separate things and should be managed in separate collections. For instance, "base_dir" is an option, whereas compat mode and experimental are attributes. The code seems to be doing the right thing, but the terminology is getting mixed up.

**Comment by ldez** [comment]
@mojavelinux `safeMode` is "attributes" or "options" ?

**Comment by ldez** [comment]
@mojavelinux and `opalPwd` ?

**Comment by mojavelinux** [comment]
Both of those are options. Here's a full list (for the Ruby API; not all work in JavaScript and no Opal-specific options are listed):

http://asciidoctor.org/docs/user-manual/#ruby-api-options

Note that the attributes are an option, so technically there is a parent, child relationship.

**Pull request merged**
