### PR TITLE
feat(highlights): encode HTML entities.

### LINKED ISSUE #241: XML closing tag U (</) disappears in preview
## Description

XML closing tag U (</) disappears in preview

- Atom version:1.17.2
- OS:max osx sierra
- `asciidoc-preview` version:2.10.1
- `language-asciidoc` version:1.10.1

## Screenshots
using asciidoc preview

using asciidocFX

## Syntax example
```adoc
[source,xml]
----
<profiles>
	<function> </function>
	<first_name></first_name>
	<last_name></last_name>
	<e-mail></e-mail>
	<company_name></company_name>
</profiles>
----
```

### PR DESCRIPTION
**Pull request by ldez**
## Description

Encode HTML entities.

## Syntax example

```adoc

[source,xml]
----
<profiles>
	<function> </function>
	<first_name></first_name>
	<last_name></last_name>
	<e-mail></e-mail>
	<company_name></company_name>
</profiles>
----

[source, html]
----
value.replace('&', '&amp;').replace('<', '&lt;')
----

[source, js]
----
value.replace('&', '&amp;').replace('<', '&lt;')
----

```

## Screenshots

html-entities

Fixes #241

### CODE REVIEW

**Comment by mojavelinux** [comment]
I really dislike "html entities" libraries because they always overdo the job. There is no reason to encode double quote as &quot; because that is only relevant if you are putting the content in the value of an attribute. That goes double for single quote. It's a sign in my mind that developers really don't know what they are doing.

The only encoding that is required for adding content to an HTML element is the following:

```
value.replace(/&/, '&amp;').replace(/</, '&lt;')
```

**Comment by ldez** [comment]
@mojavelinux before the fix:

capture d ecran de 2017-05-31 23-16-36

look the js block.

**Comment by ldez** [comment]
but your solution works also.

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
