### PR TITLE
Resolves #125, escape ': . [ ] , ( )' characters in links

### LINKED ISSUE #117: Uncaught Error: Syntax error, unrecognized expression: #../data_structure/data.adoc
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #../data_structure/data.adoc

```
At /Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:1458

Error: Syntax error, unrecognized expression: #../data_structure/data.adoc
    at Function.Sizzle.error (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:1458:8)
    at Sizzle.tokenize (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2075:11)
    at Sizzle.select (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2479:20)
    at Function.Sizzle [as find] (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2695:11)
    at [object Object].jQuery.fn.init (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:2803:38)
    at jQuery (/Users/Dio/.atom/packages/asciidoc-preview/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (/Users/Dio/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at /Users/Dio/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (/Users/Dio/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:65:72
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -2:01.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:47.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:43.3.0 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
     -1:28.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:15.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:05.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:04.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:59.5.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:58 core:move-down (atom-text-editor.editor.is-focused)
     -0:56.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:19.7.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0

# Dev
No dev packages
```

### LINKED ISSUE #125: Uncaught Error: Syntax error, unrecognized expression: #look here ()
1. Put `()` inside of `<< >>`. For example, this works fine: `hello. <<look here>>` but this shows exception: `hello. <<look here ()>>`

**Atom Version**: 1.5.4
**System**: "Fedora release
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #look here ()

```
At /usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:1458

Error: Syntax error, unrecognized expression: #look here ()
    at Function.Sizzle.error (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:1458:8)
    at Sizzle.tokenize (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2075:11)
    at Sizzle.select (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2479:20)
    at Function.Sizzle [as find] (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2695:11)
    at [object Object].jQuery.fn.init (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2803:38)
    at jQuery (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (/home/pschiffe/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at /home/pschiffe/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (/home/pschiffe/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at /usr/share/atom/resources/app.asar/src/task.js:65:72
    at /usr/share/atom/resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -2:27.4.0 core:delete (atom-text-editor.editor.is-focused)
  3x -2:27.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:26.1.0 core:delete (atom-text-editor.editor.is-focused)
     -2:23.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:07.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:07.8.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -2:02.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:01.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:10.6.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:59.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:57 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
  3x -0:45.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14 core:move-right (atom-text-editor.editor.is-focused)
 13x -0:13.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0
save-commands, v0.6.11

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #117 #115 #123 #125

### CODE REVIEW

**Comment by mojavelinux** [comment]
Could you explain why this is necessary. I trust there is a very good reason, but I want to make sure we document that reasoning in the issue so we remember in the future. Is it to make jQuery happy?

**Comment by Mogztter** [comment]
Behind the scene JQuery is using [Sizzle](https://sizzlejs.com/).
The idea is to be able to use CSS3 selector inside `$()`, for instance `:contains(text)` or `:not(a#id)`. In our case we are using a selector on an unique identifier.
But when this identifier contains parenthesis, Sizzle is trying to "execute" the expression... :boom: 

I don't have the exact list of characters that need to be escaped though.

**Comment by Mogztter** [comment]
[JQuery recommends](http://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/) to espace the following characters:
```
:
.
[
]
,
```

In addition, [Sizzle uses CSS3 selector](https://sizzlejs.com/), so we are also escaping the following characters:
```
)
(
```

During my tests, I've also notice that we do need to escape front-slash `/` in order to resolve #115

**Comment by mojavelinux** [comment]
Thank you for clarifying, @Mogztter! You nailed it on the head!

The most problematic character appears to be `/`. Asciidoctor also permits round brackets in the shorthand syntax (e.g., `[#foo(bar)]`), but I agree we should escape all the ones that jQuery recommends.

Nice work!

**Pull request merged**
