### PR TITLE
Refactor: styling

### PR DESCRIPTION
**Pull request by ldez**
update package Font Awesome to 4.6.3

### CODE REVIEW

**Comment by mojavelinux** [comment]
Is it possible to use an npm package instead of keeping the files directly in the repository? Just asking.

**Comment by ldez** [comment]
Yes is possible.

Soon, I going to rewrite template and styling.

For now fonts are references several times without build system.

**Comment by Mogztter** [comment]
I think you only need woff2 file

**Comment by ldez** [comment]
I have remove Font-Awesome bundle et AsciiDocto.js embedded style...

**Comment by ldez** [comment]
I fixed a bug (in the actual version):
- the package `file-icons` uses a non-isolated font family's name.
- `FontAwesome` that be in conflict with the `asciidoc-preview` font family.

**Comment by ldez** [comment]
Just for fun:

anim

**Pull request merged**
