### PR TITLE
refactor: split options and attributes

### PR DESCRIPTION
**Pull request by ldez**
Split options and attributes.

Related to #178 and  #169

### CODE REVIEW

**Comment by mojavelinux** [comment]
Excellent!

Technically, the most accurate thing to do is carry around attributes as a key of options. That way, you only need to pass around a single object. I have used both approaches (two separate objects or an object hierarchy) across the ecosystem. Neither approach is wrong.

**Comment by ldez** [comment]
If I create a `options-builder.coffee` with only one method who return this object :

```coffee
option =
    baseDir: '...'
    safeMode: '...'
    attributes:
        numbered: '...'
        skipFrontMatter: '...'
        # ...
```

It's a good idea or not ?

**Comment by mojavelinux** [comment]
This is good, except that the name of each attribute should match the name that actually gets passed to Asciidoctor. For instance, Asciidoctor recognizes 'skip-front-matter', not skipFrontMatter. If you want to have an interface to the actual name, then a conversion (from skipFrontMatter to skip-front-matter, for instance) needs to happen before passing the attributes to Asciidoctor.

In other words, I'd be happy with an "attributes builder" object that returns a map of the real attribute names. So you can do something like attributes.get() or something.

Btw, we really should purge the use of the name "numbered" asap. The correct name for the attribute is "sectnums".

**Comment by ldez** [comment]
you speak about that ? https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/worker.coffee

**Comment by mojavelinux** [comment]
Yes, it appears we already have an attributes builder (or you could call it a facade).

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
