### PR TITLE
Deprecated fixes

### PR DESCRIPTION
**Pull request by phdelodder**
Fix for issue #55 and #56

### CODE REVIEW

**Comment by royemmerich** [comment]
Seems like issue #55 is still not fixed by these changes. I am using atom v0.181.0 and atom-asciidoc-preview 0.4.2 with the necessary changes in this pull request added manually.

**Comment by phdelodder** [comment]
I have tested these changes and with atom v0.181.0 and, I don't get any messages from Deprecation Cop. 

Did you try the pull request?

**Comment by royemmerich** [comment]
I've just cloned your deprecated-fixes branch into my asciidoc-preview folder like this:

```
cd ~/.atom/packages
rm -rf ./asciidoc-preview/
git clone https://github.com/phdelodder/atom-asciidoc-preview.git -b deprecated-fixes ./asciidoc-preview/
```

Unfortunately the same error appears as previously reported.

**Comment by phdelodder** [comment]
Indeed, forgot to check in something, but don't have the change anymore. I have changed the pull request comment.

**Comment by anthonny** [comment]
Hi @phdelodder, @royemmerich !

@phdelodder, thank you for the PR :+1: 
I'll work on it today

**Pull request merged**
