### PR TITLE
chore: Travis CI & AppVeyor

### PR DESCRIPTION
**Pull request by ldez**
- coffeelint config
- code linting
- first spec

### CODE REVIEW

**Comment by mojavelinux** [comment]
I activated the repository from the Travis side.

**Comment by ldez** [comment]
I added AppVeyor configuration.

**Comment by mojavelinux** [comment]
Added on AppVeyor!

**Comment by mojavelinux** [comment]
Here's the badge URL: https://ci.appveyor.com/api/projects/status/a7240elaip2dkd16?svg=true

**Comment by ldez** [comment]
badge added :wink:

**Comment by Mogztter** [comment]
Thanks @ldez !

**Pull request merged**
